// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_dto.proto

package com.madchan.imsdk.lib.objects.bean.dto;

public final class MessageDTO {
  private MessageDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *消息唯一值
     * </pre>
     *
     * <code>optional uint64 message_id = 1;</code>
     */
    long getMessageId();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    int getMessageTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType getMessageType();

    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    java.lang.String getSenderId();
    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    java.lang.String getTargetId();
    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getTargetIdBytes();

    /**
     * <pre>
     *消息时间戳
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional bytes content = 6;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageLite<
          Message, Message.Builder> implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    private Message() {
      senderId_ = "";
      targetId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * Protobuf enum {@code Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <pre>
       * 未指定
       * </pre>
       *
       * <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
       */
      MESSAGE_TYPE_UNSPECIFIED(0),
      /**
       * <pre>
       * 文本消息
       * </pre>
       *
       * <code>MESSAGE_TYPE_TEXT = 1;</code>
       */
      MESSAGE_TYPE_TEXT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 未指定
       * </pre>
       *
       * <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
       */
      public static final int MESSAGE_TYPE_UNSPECIFIED_VALUE = 0;
      /**
       * <pre>
       * 文本消息
       * </pre>
       *
       * <code>MESSAGE_TYPE_TEXT = 1;</code>
       */
      public static final int MESSAGE_TYPE_TEXT_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return MESSAGE_TYPE_UNSPECIFIED;
          case 1: return MESSAGE_TYPE_TEXT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.MessageType)
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <pre>
     *消息唯一值
     * </pre>
     *
     * <code>optional uint64 message_id = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <pre>
     *消息唯一值
     * </pre>
     *
     * <code>optional uint64 message_id = 1;</code>
     */
    private void setMessageId(long value) {
      
      messageId_ = value;
    }
    /**
     * <pre>
     *消息唯一值
     * </pre>
     *
     * <code>optional uint64 message_id = 1;</code>
     */
    private void clearMessageId() {
      
      messageId_ = 0L;
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    public com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType getMessageType() {
      com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType result = com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType.forNumber(messageType_);
      return result == null ? com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    private void setMessageTypeValue(int value) {
        messageType_ = value;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    private void setMessageType(com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .Message.MessageType message_type = 2;</code>
     */
    private void clearMessageType() {
      
      messageType_ = 0;
    }

    public static final int SENDER_ID_FIELD_NUMBER = 3;
    private java.lang.String senderId_;
    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    public java.lang.String getSenderId() {
      return senderId_;
    }
    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(senderId_);
    }
    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    private void setSenderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderId_ = value;
    }
    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    private void clearSenderId() {
      
      senderId_ = getDefaultInstance().getSenderId();
    }
    /**
     * <pre>
     *消息发送用户
     * </pre>
     *
     * <code>optional string sender_id = 3;</code>
     */
    private void setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderId_ = value.toStringUtf8();
    }

    public static final int TARGET_ID_FIELD_NUMBER = 4;
    private java.lang.String targetId_;
    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    public java.lang.String getTargetId() {
      return targetId_;
    }
    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(targetId_);
    }
    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    private void setTargetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetId_ = value;
    }
    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    private void clearTargetId() {
      
      targetId_ = getDefaultInstance().getTargetId();
    }
    /**
     * <pre>
     *消息目标用户
     * </pre>
     *
     * <code>optional string target_id = 4;</code>
     */
    private void setTargetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetId_ = value.toStringUtf8();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <pre>
     *消息时间戳
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     *消息时间戳
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     *消息时间戳
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional bytes content = 6;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional bytes content = 6;</code>
     */
    private void setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>optional bytes content = 6;</code>
     */
    private void clearContent() {
      
      content_ = getDefaultInstance().getContent();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeUInt64(1, messageId_);
      }
      if (messageType_ != com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType.MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (!senderId_.isEmpty()) {
        output.writeString(3, getSenderId());
      }
      if (!targetId_.isEmpty()) {
        output.writeString(4, getTargetId());
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(5, timestamp_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(6, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, messageId_);
      }
      if (messageType_ != com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType.MESSAGE_TYPE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (!senderId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSenderId());
      }
      if (!targetId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getTargetId());
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, timestamp_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, content_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message, Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.MessageOrBuilder {
      // Construct using com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *消息唯一值
       * </pre>
       *
       * <code>optional uint64 message_id = 1;</code>
       */
      public long getMessageId() {
        return instance.getMessageId();
      }
      /**
       * <pre>
       *消息唯一值
       * </pre>
       *
       * <code>optional uint64 message_id = 1;</code>
       */
      public Builder setMessageId(long value) {
        copyOnWrite();
        instance.setMessageId(value);
        return this;
      }
      /**
       * <pre>
       *消息唯一值
       * </pre>
       *
       * <code>optional uint64 message_id = 1;</code>
       */
      public Builder clearMessageId() {
        copyOnWrite();
        instance.clearMessageId();
        return this;
      }

      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional .Message.MessageType message_type = 2;</code>
       */
      public int getMessageTypeValue() {
        return instance.getMessageTypeValue();
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional .Message.MessageType message_type = 2;</code>
       */
      public Builder setMessageTypeValue(int value) {
        copyOnWrite();
        instance.setMessageTypeValue(value);
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional .Message.MessageType message_type = 2;</code>
       */
      public com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType getMessageType() {
        return instance.getMessageType();
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional .Message.MessageType message_type = 2;</code>
       */
      public Builder setMessageType(com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.MessageType value) {
        copyOnWrite();
        instance.setMessageType(value);
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>optional .Message.MessageType message_type = 2;</code>
       */
      public Builder clearMessageType() {
        copyOnWrite();
        instance.clearMessageType();
        return this;
      }

      /**
       * <pre>
       *消息发送用户
       * </pre>
       *
       * <code>optional string sender_id = 3;</code>
       */
      public java.lang.String getSenderId() {
        return instance.getSenderId();
      }
      /**
       * <pre>
       *消息发送用户
       * </pre>
       *
       * <code>optional string sender_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        return instance.getSenderIdBytes();
      }
      /**
       * <pre>
       *消息发送用户
       * </pre>
       *
       * <code>optional string sender_id = 3;</code>
       */
      public Builder setSenderId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSenderId(value);
        return this;
      }
      /**
       * <pre>
       *消息发送用户
       * </pre>
       *
       * <code>optional string sender_id = 3;</code>
       */
      public Builder clearSenderId() {
        copyOnWrite();
        instance.clearSenderId();
        return this;
      }
      /**
       * <pre>
       *消息发送用户
       * </pre>
       *
       * <code>optional string sender_id = 3;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息目标用户
       * </pre>
       *
       * <code>optional string target_id = 4;</code>
       */
      public java.lang.String getTargetId() {
        return instance.getTargetId();
      }
      /**
       * <pre>
       *消息目标用户
       * </pre>
       *
       * <code>optional string target_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTargetIdBytes() {
        return instance.getTargetIdBytes();
      }
      /**
       * <pre>
       *消息目标用户
       * </pre>
       *
       * <code>optional string target_id = 4;</code>
       */
      public Builder setTargetId(
          java.lang.String value) {
        copyOnWrite();
        instance.setTargetId(value);
        return this;
      }
      /**
       * <pre>
       *消息目标用户
       * </pre>
       *
       * <code>optional string target_id = 4;</code>
       */
      public Builder clearTargetId() {
        copyOnWrite();
        instance.clearTargetId();
        return this;
      }
      /**
       * <pre>
       *消息目标用户
       * </pre>
       *
       * <code>optional string target_id = 4;</code>
       */
      public Builder setTargetIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTargetIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息时间戳
       * </pre>
       *
       * <code>optional uint64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       *消息时间戳
       * </pre>
       *
       * <code>optional uint64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       *消息时间戳
       * </pre>
       *
       * <code>optional uint64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional bytes content = 6;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return instance.getContent();
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional bytes content = 6;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>optional bytes content = 6;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message other = (com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message) arg1;
          messageId_ = visitor.visitLong(messageId_ != 0L, messageId_,
              other.messageId_ != 0L, other.messageId_);
          messageType_ = visitor.visitInt(messageType_ != 0, messageType_,    other.messageType_ != 0, other.messageType_);
          senderId_ = visitor.visitString(!senderId_.isEmpty(), senderId_,
              !other.senderId_.isEmpty(), other.senderId_);
          targetId_ = visitor.visitString(!targetId_.isEmpty(), targetId_,
              !other.targetId_.isEmpty(), other.targetId_);
          timestamp_ = visitor.visitLong(timestamp_ != 0L, timestamp_,
              other.timestamp_ != 0L, other.timestamp_);
          content_ = visitor.visitByteString(content_ != com.google.protobuf.ByteString.EMPTY, content_,
              other.content_ != com.google.protobuf.ByteString.EMPTY, other.content_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  messageId_ = input.readUInt64();
                  break;
                }
                case 16: {
                  int rawValue = input.readEnum();

                  messageType_ = rawValue;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  senderId_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  targetId_ = s;
                  break;
                }
                case 40: {

                  timestamp_ = input.readUInt64();
                  break;
                }
                case 50: {

                  content_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Message)
    private static final com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.madchan.imsdk.lib.objects.bean.dto.MessageDTO.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Message> PARSER;

    public static com.google.protobuf.Parser<Message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
